#!/usr/bin/env python3
'''
Qing Li, 20170131
'''

def main():
    '''
    This script searches for bibliography record in the MyLibrary.bib
    file with the input keyword (citation key) and writes the full record
    to the destination file.
    '''

    import sys
    import re
    import os

    usage_str = '''Usage:
        addbib_core [Keyword] [RefFile]
               Print on screen if no RefFile is specified.
    '''
    narg = len(sys.argv)
    if narg == 3:
        l_write = 1
        destfile = sys.argv[2]
    elif narg == 2:
        l_write = 0
    else:
        print(usage_str)
        sys.exit(2)

    # Set the bibliography library environment when called for
    # the first time
    homedir = os.path.expanduser('~')
    biblib = homedir+'/.addbib_lib'

    # check if the environment file exist
    if os.path.isfile(biblib):
        with open(biblib, 'r') as infile:
            srcfile = infile.read()
        l_biblib = 0
    else:
        l_biblib = 1

    # Check if the bibliography library is properly set
    if os.path.isfile(srcfile):
        l_srcfile = 0
    else:
        l_srcfile = 1

    # Update the environment if necessary
    if l_biblib or l_srcfile:
        while True:
            srcfile = input('Where is the bibliography library file?\n')
            if os.path.isfile(srcfile):
                break
            else:
                print('Bib lib {} not exist.\n'.format(srcfile))
        with open(biblib, 'w') as outfile:
            outfile.write(srcfile)

    keyname = sys.argv[1]
    keyprefix = r'@.*{'
    keyre = keyprefix+keyname+','

    # Check whether the record exists in the destination file
    if l_write and os.path.isfile(destfile):
        for line in open(destfile, 'r'):
            if re.search(keyre, line):
                print('The record '+keyname+' is already in '+destfile+'\n')
                sys.exit(0)

    # Find all the full record
    l_found = 0
    with open(srcfile, 'r') as infile:
        for line in infile:
            if re.search(keyre, line):
                l_found = 1
                newline = next(infile)
                rec_info = line
                while not re.search(keyprefix, newline):
                    rec_info += newline
                    newline = next(infile)

    # Write to the destination file
    if l_found == 0:
        print('Keyword '+keyname+' not found.\n')
    else:
        print('Bibliography:')
        print('--------')
        print(rec_info)
        if l_write:
            print('Writing record '+keyname+' to file '+destfile+'...\n')
            with open(destfile, 'a+') as outfile:
                outfile.write(rec_info)

if __name__ == "__main__":
    main()
