#!/usr/bin/env python3
'''
Qing Li, 20170131
'''

def main():
    '''
    This script calls addbib_core to add multiple bibliography records to the
    destination file at the same time.
    '''
    import sys
    import re
    import subprocess

    usage_str = '''Usage:
        addbib [Keyword1] [Keyword2] ... [RefFile]
               Print on screen if no RefFile is specified.
    '''

    nargv = len(sys.argv)
    if nargv < 2:
        print(usage_str)
        sys.exit(2)

    destfile = sys.argv[nargv-1]
    keyre = r'[A-Za-z]*[0-9]{4},*'
    if re.search(keyre, destfile):
        keylist = sys.argv[1:nargv]
        l_write = 0
    else:
        keylist = sys.argv[1:nargv-1]
        l_write = 1

    for keyname in keylist:
        keyname = keyname.strip(',')
        if l_write:
            cp = subprocess.run(['addbib_core', keyname, destfile])
        else:
            cp = subprocess.run(['addbib_core', keyname])
        cp.check_returncode()

if __name__ == "__main__":
    main()
